---
- include_tasks: unpack.yml

- name: set repo path
  set_fact:
    git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"

- name: git add all new files
  shell: git add -A
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"

- name: git status
  shell: git status
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"
  register: git_add_status

- name: git commit
  shell: git commit -a -m "'{{ git_msg }}'"
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"
  ignore_errors: true

- name: git push
  shell: git push --force
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"
  environment:
    GIT_SSH_COMMAND: "ssh -i '{{ git_temp_file.path }}' -F /dev/null"

- name: git status
  shell: git status
  args:
    chdir: "{{ playbook_dir }}/{{ git_repo_path }}"
  register: git_add_status

- include_tasks: cleanup_keys.yml
