---
- include_tasks: unpack.yml

- name: set repo path
  set_fact:
    git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"

- name: git add all new files
  shell: git add -A
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"

- name: git status
  shell: git status
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"
  register: git_add_status

- name: git commit
  shell: git commit -a -m "'{{ git_msg }}'"
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"
  ignore_errors: true

- name: git wrapper
  copy:
    dest: "{{ playbook_dir }}/.ssh/ssh"
    content: "ssh -i {{ git_temp_file.path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $*"
    mode: 0700

- name: git push
  shell: git push --force
  args:
    chdir: "{{ playbook_dir }}{{ git_repo_path }}"
  environment:
    GIT_SSH: "{{ playbook_dir }}/.ssh/ssh"

- name: git status
  shell: git status
  args:
    chdir: "{{ playbook_dir }}/{{ git_repo_path }}"
  register: git_add_status

- include_tasks: cleanup_keys.yml
